name: Continuous Integration
on: 
  push:
    branches:
      - main
jobs:
  build:

    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/ssh-action@master
      with:
        host:  ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        envs: GITHUB_SHA
        script: cd ~/serenote && git fetch && git checkout $GITHUB_SHA && docker-compose up -d --build
